<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="OutputDevices\SerializableServos.cs" />
    <Compile Remove="Utilities\ConfigureServos.cs" />
    <Compile Remove="Utilities\SerializableMovies.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="OutputDevices\Adobe Creative Cloud.lnk" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.0" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExternalRequired\ArduinoCode\" />
  </ItemGroup>

</Project>
