use super::config::*;
use crate::input::manager::InputState;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

/// A scalar command the input mapper produced for the WS client.
/// Either a raw ROS topic/channel write (legacy) or a WS-input write
/// (new path). The runtime dispatches each variant to the matching
/// WebSocketClient method.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum MappedCommand {
    Topic {
        topic: String,
        channel: String,
        value: Value,
    },
    WsInput {
        sheet_id: String,
        input_id: String,
        value: Value,
    },
}

impl MappedCommand {
    fn from_target(target: &super::config::ControlTarget, value: Value) -> Self {
        match target {
            super::config::ControlTarget::Topic { topic, channel, .. } =>
                MappedCommand::Topic {
                    topic: topic.clone(),
                    channel: channel.clone(),
                    value,
                },
            super::config::ControlTarget::WsInput { sheet_id, input_id, .. } =>
                MappedCommand::WsInput {
                    sheet_id: sheet_id.clone(),
                    input_id: input_id.clone(),
                    value,
                },
        }
    }

}

/// Action events generated by input processing
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ActionEvent {
    /// Send a control command
    Command(MappedCommand),
    /// Show a preset panel
    ShowPanel { panel_id: String },
    /// Hide the current panel
    HidePanel,
    /// Navigate within a panel
    NavigatePanel { direction: NavigateDirection },
    /// Select the current panel item
    SelectPanelItem,
    /// Activate a specific preset
    ActivatePreset { preset_id: String },
    /// Toggle an output
    ToggleOutput { target_id: String },
    /// Cycle through output values
    CycleOutput { target_id: String, value: String },
    /// Emergency stop
    EStop,
}

/// Panel navigation state
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PanelState {
    pub active_panel_id: Option<String>,
    pub selected_index: usize,
    pub current_page: usize,
}

/// Saved profiles structure for persistence
#[derive(Debug, Clone, Serialize, Deserialize)]
struct SavedProfiles {
    profiles: Vec<BindingProfile>,
    active_profile_id: String,
}

/// Maps input state to commands and actions based on bindings
pub struct InputMapper {
    profiles: Vec<BindingProfile>,
    active_profile_id: String,
    last_analog_values: HashMap<String, f32>,
    /// Wall-clock of the last send per analog key. Drives the heartbeat
    /// re-send so a dropped dead-stick packet doesn't permanently strand
    /// the motor — every `HEARTBEAT_MS` we re-emit the current value
    /// regardless of change detection.
    last_send_times: HashMap<String, std::time::Instant>,
    last_button_states: HashMap<String, bool>,
    panel_state: PanelState,
    cycle_indices: HashMap<String, usize>,
    toggle_states: HashMap<String, bool>,
    modifier_values: HashMap<String, f32>,
}

/// Force re-send each analog target this often even if change detection
/// says nothing new — protects against dropped dead-stick (return-to-zero)
/// packets, post-reconnect drift, and the firmware coming back from a
/// brown-out reset while the operator's hands are off the stick.
const HEARTBEAT_MS: u64 = 500;

impl InputMapper {
    pub fn new() -> Self {
        // Try to load profiles from disk, fall back to defaults
        let (profiles, active_profile_id) = Self::load_profiles_from_disk()
            .unwrap_or_else(|| {
                log::info!("No saved profiles found, using defaults");
                (vec![super::presets::create_default_profile()], "default".to_string())
            });

        Self {
            profiles,
            active_profile_id,
            last_analog_values: HashMap::new(),
            last_send_times: HashMap::new(),
            last_button_states: HashMap::new(),
            panel_state: PanelState::default(),
            cycle_indices: HashMap::new(),
            toggle_states: HashMap::new(),
            modifier_values: HashMap::new(),
        }
    }

    /// Get the profiles config file path
    fn get_profiles_path() -> Option<PathBuf> {
        dirs::data_dir().map(|p| p.join("com.saintos.controller").join("profiles.json"))
    }

    /// Load profiles from disk
    fn load_profiles_from_disk() -> Option<(Vec<BindingProfile>, String)> {
        let path = Self::get_profiles_path()?;
        if !path.exists() {
            return None;
        }

        let content = fs::read_to_string(&path).ok()?;
        let saved: SavedProfiles = serde_json::from_str(&content).ok()?;
        log::info!("Loaded {} profiles from {:?}", saved.profiles.len(), path);
        Some((saved.profiles, saved.active_profile_id))
    }

    /// Save profiles to disk
    pub fn save_profiles_to_disk(&self) {
        if let Some(path) = Self::get_profiles_path() {
            // Ensure directory exists
            if let Some(parent) = path.parent() {
                let _ = fs::create_dir_all(parent);
            }

            let saved = SavedProfiles {
                profiles: self.profiles.clone(),
                active_profile_id: self.active_profile_id.clone(),
            };

            match serde_json::to_string_pretty(&saved) {
                Ok(json) => {
                    if let Err(e) = fs::write(&path, json) {
                        log::error!("Failed to save profiles to {:?}: {}", path, e);
                    } else {
                        log::info!("Saved {} profiles to {:?}", self.profiles.len(), path);
                    }
                }
                Err(e) => {
                    log::error!("Failed to serialize profiles: {}", e);
                }
            }
        }
    }

    pub fn get_profiles(&self) -> &[BindingProfile] {
        &self.profiles
    }

    pub fn set_profiles(&mut self, profiles: Vec<BindingProfile>) {
        self.profiles = profiles;
        if !self.profiles.iter().any(|p| p.id == self.active_profile_id) {
            self.active_profile_id = self
                .profiles
                .first()
                .map(|p| p.id.clone())
                .unwrap_or_default();
        }
        // Persist to disk
        self.save_profiles_to_disk();
    }

    pub fn set_active_profile(&mut self, profile_id: &str) {
        if self.profiles.iter().any(|p| p.id == profile_id) {
            self.active_profile_id = profile_id.to_string();
            // Persist to disk
            self.save_profiles_to_disk();
        }
    }

    pub fn active_profile(&self) -> Option<&BindingProfile> {
        self.profiles
            .iter()
            .find(|p| p.id == self.active_profile_id)
    }

    #[allow(dead_code)] // panel state is owned/driven from the frontend today
    pub fn panel_state(&self) -> &PanelState {
        &self.panel_state
    }

    /// Process input state and generate action events
    pub fn process(&mut self, input: &InputState) -> Vec<ActionEvent> {
        // Move the profiles Vec out of `self` so the active profile can
        // be borrowed immutably while process_*_bindings hold &mut self
        // (for the change-detection caches). This replaces a full
        // BindingProfile CLONE on every 60 Hz frame — the profile carries
        // Vecs of analog + digital bindings, panels, and presets, so that
        // clone dominated the per-frame cost (~5.5 µs). mem::take swaps in
        // an empty Vec (cheap) and we restore it before returning; the
        // binding helpers never read self.profiles, so the temporarily-
        // empty Vec is never observed.
        let profiles = std::mem::take(&mut self.profiles);
        let mut events = Vec::new();
        if let Some(idx) = profiles.iter().position(|p| p.id == self.active_profile_id) {
            let profile = &profiles[idx];
            self.process_analog_bindings(profile, input, &mut events);
            self.process_digital_bindings(profile, input, &mut events);
        }
        self.profiles = profiles; // restore
        events
    }

    fn process_analog_bindings(
        &mut self,
        profile: &BindingProfile,
        input: &InputState,
        events: &mut Vec<ActionEvent>,
    ) {
        for binding in &profile.analog_bindings {
            if !binding.enabled {
                continue;
            }

            let raw_value = self.get_analog_value(input, &binding.input);

            match &binding.action {
                AnalogAction::DirectControl { target, transform } => {
                    // Sticks/triggers/touchpads use normalized -1..1 values.
                    // Gyro axes are different: InputState stores angular velocity
                    // in degrees/second, and we intentionally preserve those
                    // physical units on the wire for direct-control bindings.
                    let is_gyro = binding.input.is_gyro();
                    let transformed = if is_gyro {
                        transform.apply_gyro_dps(raw_value)
                    } else {
                        transform.apply(raw_value)
                    };

                    // Apply trigger-based modifiers.  The normal path clamps to
                    // -1..1; gyro must remain in deg/s, so use the unclamped
                    // modifier path and cap only at the sensor full-scale.
                    let modified = if is_gyro {
                        self.apply_modifiers_unclamped(transformed)
                            .clamp(-GYRO_FULL_SCALE_DPS, GYRO_FULL_SCALE_DPS)
                    } else {
                        self.apply_modifiers(transformed)
                    };

                    // Key the change-detection cache by (input, target) —
                    // not just by input. Tank-style setups bind the same
                    // gamepad axis to two targets (one per track-drive
                    // sheet), and if both share a single "LeftStickY"
                    // cache entry, the first iteration's stick-release
                    // event clobbers `last` to 0 and the second target
                    // sees no change → never sends its zero → its motor
                    // sticks at the last commanded velocity.
                    let target_key = match target {
                        super::config::ControlTarget::Topic { topic, channel, .. } =>
                            format!("topic::{}::{}", topic, channel),
                        super::config::ControlTarget::WsInput { sheet_id, input_id, .. } =>
                            format!("ws::{}::{}", sheet_id, input_id),
                    };
                    let key = format!("{:?}::{}", binding.input, target_key);
                    let last = self.last_analog_values.get(&key).copied().unwrap_or(0.0);
                    let delta = (modified - last).abs();

                    // Send command if:
                    // 1. Value changed significantly (delta > 0.001), OR
                    // 2. Value is non-zero (keep sending for continuous control), OR
                    // 3. Value just returned to zero (send final stop command), OR
                    // 4. Heartbeat — re-assert current value periodically so a
                    //    dropped packet (Wi-Fi blip, firmware brown-out reboot,
                    //    server reconnect, etc.) can't permanently strand the
                    //    motor at a non-zero value.
                    // The WebSocket client's per-target throttle
                    // (THROTTLE_MS in protocol/client.rs) paces the wire.
                    let value_changed = delta > 0.001;
                    let value_active = modified.abs() > 0.001;
                    let returned_to_zero = last.abs() > 0.001 && modified.abs() <= 0.001;
                    let heartbeat_due = match self.last_send_times.get(&key) {
                        Some(t) => t.elapsed() >= std::time::Duration::from_millis(HEARTBEAT_MS),
                        None => true,
                    };
                    let should_send = value_changed || value_active || returned_to_zero || heartbeat_due;

                    if should_send {
                        self.last_analog_values.insert(key.clone(), modified);
                        self.last_send_times.insert(key, std::time::Instant::now());

                        events.push(ActionEvent::Command(MappedCommand::from_target(
                            target,
                            Value::from(modified),
                        )));
                    }
                }
                AnalogAction::DifferentialDrive {
                    topic,
                    left_channel,
                    right_channel,
                    throttle_transform,
                    turn_transform,
                } => {
                    // Get both stick axes based on which axis this binding is for
                    // DifferentialDrive should be bound to the Y axis (throttle) of a stick
                    let (throttle_raw, turn_raw) = match &binding.input {
                        AnalogInput::LeftStickY => (
                            input.gamepad.left_stick.y,
                            input.gamepad.left_stick.x,
                        ),
                        AnalogInput::RightStickY => (
                            input.gamepad.right_stick.y,
                            input.gamepad.right_stick.x,
                        ),
                        // If bound to X axis, swap the interpretation
                        AnalogInput::LeftStickX => (
                            input.gamepad.left_stick.y,
                            input.gamepad.left_stick.x,
                        ),
                        AnalogInput::RightStickX => (
                            input.gamepad.right_stick.y,
                            input.gamepad.right_stick.x,
                        ),
                        // Trackpads: throttle = y, turn = x, same as a stick
                        // (either axis of the pad selects the whole pad).
                        AnalogInput::LeftPadX | AnalogInput::LeftPadY => (
                            input.left_touchpad.y,
                            input.left_touchpad.x,
                        ),
                        AnalogInput::RightPadX | AnalogInput::RightPadY => (
                            input.right_touchpad.y,
                            input.right_touchpad.x,
                        ),
                        // Triggers don't make sense for differential drive
                        _ => continue,
                    };

                    // Apply transforms
                    let throttle = self.apply_modifiers(throttle_transform.apply(throttle_raw));
                    let turn = self.apply_modifiers(turn_transform.apply(turn_raw));

                    // Channel mixing: left = throttle + turn, right = throttle - turn
                    let mut left = throttle + turn;
                    let mut right = throttle - turn;

                    // Normalize if either exceeds bounds (proportional scaling)
                    let max_val = left.abs().max(right.abs());
                    if max_val > 1.0 {
                        left /= max_val;
                        right /= max_val;
                    }

                    // Check if we should send (same logic as DirectControl but for the combined values).
                    // Match DirectControl's heartbeat behaviour: re-emit
                    // the current values periodically so a dropped
                    // deadstick packet doesn't permanently strand the
                    // motors. Without this, a single lost UDP frame on
                    // return-to-zero leaves both tracks running at the
                    // last commanded velocity until the operator nudges
                    // the stick again.
                    let key_left = format!("{}::{}", topic, left_channel);
                    let key_right = format!("{}::{}", topic, right_channel);
                    let last_left = self.last_analog_values.get(&key_left).copied().unwrap_or(0.0);
                    let last_right = self.last_analog_values.get(&key_right).copied().unwrap_or(0.0);

                    let delta_left = (left - last_left).abs();
                    let delta_right = (right - last_right).abs();
                    let any_changed = delta_left > 0.001 || delta_right > 0.001;
                    let any_active = left.abs() > 0.001 || right.abs() > 0.001;
                    let returned_to_zero = (last_left.abs() > 0.001 || last_right.abs() > 0.001)
                        && left.abs() <= 0.001 && right.abs() <= 0.001;
                    // Heartbeat is keyed on the LEFT slot but covers both —
                    // they're always sent together, so a single timer
                    // tracks the pair correctly.
                    let heartbeat_due = match self.last_send_times.get(&key_left) {
                        Some(t) => t.elapsed() >= std::time::Duration::from_millis(HEARTBEAT_MS),
                        None => true,
                    };
                    let should_send = any_changed || any_active || returned_to_zero || heartbeat_due;

                    if should_send {
                        self.last_analog_values.insert(key_left.clone(), left);
                        self.last_analog_values.insert(key_right, right);
                        let now = std::time::Instant::now();
                        self.last_send_times.insert(key_left, now);

                        // Send both left and right commands. Differential
                        // drive stays on the raw topic/channel path — the
                        // server-side routing graph is where the operator
                        // mixes individual WS inputs into tank-drive
                        // commands.
                        events.push(ActionEvent::Command(MappedCommand::Topic {
                            topic: topic.clone(),
                            channel: left_channel.clone(),
                            value: Value::from(left),
                        }));
                        events.push(ActionEvent::Command(MappedCommand::Topic {
                            topic: topic.clone(),
                            channel: right_channel.clone(),
                            value: Value::from(right),
                        }));
                    }
                }
                AnalogAction::Modifier { effect } => {
                    // Modifiers are conceptually normalized controls. If a gyro
                    // axis is deliberately used as one, normalize its deg/s
                    // reading to -1..1 before storing it.
                    let modifier_value = if binding.input.is_gyro() {
                        (raw_value / GYRO_FULL_SCALE_DPS).clamp(-1.0, 1.0)
                    } else {
                        raw_value
                    };

                    // Store modifier value for use by other bindings
                    match effect {
                        ModifierEffect::PrecisionMode { .. } => {
                            self.modifier_values.insert("precision".to_string(), modifier_value);
                        }
                        ModifierEffect::SpeedBoost { .. } => {
                            self.modifier_values.insert("speed_boost".to_string(), modifier_value);
                        }
                        ModifierEffect::ScaleTarget { target_id, .. } => {
                            self.modifier_values.insert(target_id.clone(), modifier_value);
                        }
                    }
                }
            }
        }
    }

    fn process_digital_bindings(
        &mut self,
        profile: &BindingProfile,
        input: &InputState,
        events: &mut Vec<ActionEvent>,
    ) {
        for binding in &profile.digital_bindings {
            if !binding.enabled {
                continue;
            }

            let pressed = self.get_button_pressed(input, &binding.input);
            let key = format!("{:?}", binding.input);
            let was_pressed = self.last_button_states.get(&key).copied().unwrap_or(false);
            self.last_button_states.insert(key.clone(), pressed);

            // For now, handle Press trigger (TODO: implement Hold, DoubleTap, LongPress)
            let triggered = match binding.trigger {
                ButtonTrigger::Press => pressed && !was_pressed,
                ButtonTrigger::Release => !pressed && was_pressed,
                _ => false, // TODO: implement other triggers
            };

            if !triggered {
                continue;
            }

            match &binding.action {
                DigitalAction::ShowPanel { panel_id } => {
                    if self.panel_state.active_panel_id.as_ref() == Some(panel_id) {
                        // Toggle off if same panel
                        self.panel_state.active_panel_id = None;
                        events.push(ActionEvent::HidePanel);
                    } else {
                        self.panel_state.active_panel_id = Some(panel_id.clone());
                        self.panel_state.selected_index = 0;
                        self.panel_state.current_page = 0;
                        events.push(ActionEvent::ShowPanel {
                            panel_id: panel_id.clone(),
                        });
                    }
                }
                DigitalAction::HidePanel => {
                    self.panel_state.active_panel_id = None;
                    events.push(ActionEvent::HidePanel);
                }
                DigitalAction::NavigatePanel { direction } => {
                    if self.panel_state.active_panel_id.is_some() {
                        self.navigate_panel(profile, direction);
                        events.push(ActionEvent::NavigatePanel {
                            direction: direction.clone(),
                        });
                    }
                }
                DigitalAction::SelectPanelItem => {
                    if let Some(panel_id) = &self.panel_state.active_panel_id {
                        if let Some(panel) = profile.get_panel(panel_id) {
                            if let Some(preset) = panel.presets.get(self.panel_state.selected_index)
                            {
                                events.push(ActionEvent::ActivatePreset {
                                    preset_id: preset.id.clone(),
                                });
                            }
                        }
                    }
                }
                DigitalAction::ActivatePreset { preset_id } => {
                    events.push(ActionEvent::ActivatePreset {
                        preset_id: preset_id.clone(),
                    });
                }
                DigitalAction::ToggleOutput { target_id } => {
                    let current = self.toggle_states.get(target_id).copied().unwrap_or(false);
                    self.toggle_states.insert(target_id.clone(), !current);
                    events.push(ActionEvent::ToggleOutput {
                        target_id: target_id.clone(),
                    });
                }
                DigitalAction::CycleOutput { target_id, values } => {
                    if !values.is_empty() {
                        let idx = self.cycle_indices.get(target_id).copied().unwrap_or(0);
                        let next_idx = (idx + 1) % values.len();
                        self.cycle_indices.insert(target_id.clone(), next_idx);
                        events.push(ActionEvent::CycleOutput {
                            target_id: target_id.clone(),
                            value: values[next_idx].clone(),
                        });
                    }
                }
                DigitalAction::DirectControl { target, value } => {
                    events.push(ActionEvent::Command(MappedCommand::from_target(
                        target,
                        Value::from(*value),
                    )));
                }
                DigitalAction::EStop => {
                    events.push(ActionEvent::EStop);
                }
                DigitalAction::None => {}
            }
        }
    }

    fn navigate_panel(&mut self, profile: &BindingProfile, direction: &NavigateDirection) {
        if let Some(panel_id) = &self.panel_state.active_panel_id {
            if let Some(panel) = profile.get_panel(panel_id) {
                let total_items = panel.presets.len();
                let columns = panel.columns as usize;
                let items_per_page = panel.items_per_page as usize;
                let total_pages = total_items.div_ceil(items_per_page);

                match direction {
                    // Grid navigation
                    NavigateDirection::Up => {
                        if self.panel_state.selected_index >= columns {
                            self.panel_state.selected_index -= columns;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::Down => {
                        if self.panel_state.selected_index + columns < total_items {
                            self.panel_state.selected_index += columns;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::Left => {
                        if self.panel_state.selected_index > 0 {
                            self.panel_state.selected_index -= 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::Right => {
                        if self.panel_state.selected_index + 1 < total_items {
                            self.panel_state.selected_index += 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    // Linear navigation
                    NavigateDirection::NextItem => {
                        if self.panel_state.selected_index + 1 < total_items {
                            self.panel_state.selected_index += 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::PrevItem => {
                        if self.panel_state.selected_index > 0 {
                            self.panel_state.selected_index -= 1;
                            self.panel_state.current_page =
                                self.panel_state.selected_index / items_per_page;
                        }
                    }
                    NavigateDirection::NextPage => {
                        if self.panel_state.current_page + 1 < total_pages {
                            self.panel_state.current_page += 1;
                            self.panel_state.selected_index =
                                self.panel_state.current_page * items_per_page;
                        }
                    }
                    NavigateDirection::PrevPage => {
                        if self.panel_state.current_page > 0 {
                            self.panel_state.current_page -= 1;
                            self.panel_state.selected_index =
                                self.panel_state.current_page * items_per_page;
                        }
                    }
                }
            }
        }
    }

    fn get_analog_value(&self, input: &InputState, analog: &AnalogInput) -> f32 {
        match analog {
            AnalogInput::LeftStickX => input.gamepad.left_stick.x,
            AnalogInput::LeftStickY => input.gamepad.left_stick.y,
            AnalogInput::RightStickX => input.gamepad.right_stick.x,
            AnalogInput::RightStickY => input.gamepad.right_stick.y,
            AnalogInput::LeftTrigger => input.gamepad.left_trigger,
            AnalogInput::RightTrigger => input.gamepad.right_trigger,
            AnalogInput::LeftPadX => input.left_touchpad.x,
            AnalogInput::LeftPadY => input.left_touchpad.y,
            AnalogInput::RightPadX => input.right_touchpad.x,
            AnalogInput::RightPadY => input.right_touchpad.y,
            AnalogInput::GyroPitch => input.gyro.pitch,
            AnalogInput::GyroRoll => input.gyro.roll,
            AnalogInput::GyroYaw => input.gyro.yaw,
        }
    }

    fn get_button_pressed(&self, input: &InputState, button: &DigitalInput) -> bool {
        let button_name = match button {
            DigitalInput::A => "A",
            DigitalInput::B => "B",
            DigitalInput::X => "X",
            DigitalInput::Y => "Y",
            DigitalInput::LB => "LB",
            DigitalInput::RB => "RB",
            DigitalInput::DPadUp => "DPadUp",
            DigitalInput::DPadDown => "DPadDown",
            DigitalInput::DPadLeft => "DPadLeft",
            DigitalInput::DPadRight => "DPadRight",
            DigitalInput::Start => "Start",
            DigitalInput::Select => "Select",
            DigitalInput::LeftStick => "LeftStick",
            DigitalInput::RightStick => "RightStick",
            // Steam Deck back buttons
            DigitalInput::L4 => "L4",
            DigitalInput::R4 => "R4",
            DigitalInput::L5 => "L5",
            DigitalInput::R5 => "R5",
            DigitalInput::Steam => "Steam",
        };
        input.gamepad.buttons.get(button_name).copied().unwrap_or(false)
    }

    fn apply_modifiers_unclamped(&self, value: f32) -> f32 {
        let mut result = value;

        // Apply precision mode (reduces output based on left trigger)
        if let Some(&precision) = self.modifier_values.get("precision") {
            if precision > 0.0 {
                // At full trigger, reduce to min_scale (e.g., 0.3)
                let min_scale = 0.3;
                let scale = 1.0 - (precision * (1.0 - min_scale));
                result *= scale;
            }
        }

        // Apply speed boost (increases output based on right trigger)
        if let Some(&boost) = self.modifier_values.get("speed_boost") {
            if boost > 0.0 {
                let max_boost = 1.5;
                let scale = 1.0 + (boost * (max_boost - 1.0));
                result *= scale;
            }
        }

        result
    }

    fn apply_modifiers(&self, value: f32) -> f32 {
        self.apply_modifiers_unclamped(value).clamp(-1.0, 1.0)
    }
}

impl Default for InputMapper {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    //! Behavior lock-down + perf benchmarks for the per-frame input
    //! mapping hot path. Benches are #[ignore]d so they stay out of the
    //! normal `cargo test` run; invoke them with:
    //!   cargo test --release --lib -- --ignored --nocapture bench
    //!
    //! We set the mapper's private fields directly rather than calling
    //! set_profiles()/set_active_profile() — those persist to the real
    //! user data dir (profiles.json) and a test must not clobber the
    //! operator's saved profiles.
    use super::*;
    use crate::bindings::config::*;
    use crate::input::gamepad::GamepadState;
    use crate::input::gyro::{GyroState, TouchpadState};
    use crate::input::manager::InputState;
    use std::time::Instant;

    fn approx(a: f32, b: f32) {
        assert!((a - b).abs() < 1e-5, "expected {b}, got {a}");
    }

    // Identity transform (no deadzone/expo/scale) so binding-level math
    // is exercised without the per-axis transform muddying the numbers —
    // InputTransform::apply has its own dedicated tests in config.rs.
    fn tf0() -> InputTransform {
        InputTransform { deadzone: 0.0, scale: 1.0, expo: 1.0, invert: false }
    }

    fn mapper_with(profile: BindingProfile) -> InputMapper {
        let mut m = InputMapper::new();
        let id = profile.id.clone();
        m.profiles = vec![profile];
        m.active_profile_id = id;
        m.last_analog_values.clear();
        m.last_send_times.clear();
        m.last_button_states.clear();
        m.modifier_values.clear();
        m.toggle_states.clear();
        m.cycle_indices.clear();
        m.panel_state = PanelState::default();
        m
    }

    fn analog_profile(binding: AnalogBinding) -> BindingProfile {
        let mut p = BindingProfile::new("test", "Test");
        p.analog_bindings = vec![binding];
        p
    }

    fn digital_profile(binding: DigitalBinding) -> BindingProfile {
        let mut p = BindingProfile::new("test", "Test");
        p.digital_bindings = vec![binding];
        p
    }

    fn input_right_stick(x: f32, y: f32) -> InputState {
        let mut gp = GamepadState { connected: true, ..Default::default() };
        gp.right_stick.x = x;
        gp.right_stick.y = y;
        InputState {
            gamepad: gp,
            gyro: GyroState::default(),
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    fn input_gyro(pitch: f32, roll: f32, yaw: f32) -> InputState {
        InputState {
            gamepad: GamepadState { connected: true, ..Default::default() },
            gyro: GyroState { pitch, roll, yaw },
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    fn input_buttons(pairs: &[(&str, bool)]) -> InputState {
        let mut gp = GamepadState { connected: true, ..Default::default() };
        for (name, pressed) in pairs {
            gp.buttons.insert((*name).to_string(), *pressed);
        }
        InputState {
            gamepad: gp,
            gyro: GyroState::default(),
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    // Value written to a specific Topic channel, if any command targets it.
    fn topic_cmd(events: &[ActionEvent], channel: &str) -> Option<f64> {
        for e in events {
            if let ActionEvent::Command(MappedCommand::Topic { channel: c, value, .. }) = e {
                if c == channel {
                    return value.as_f64();
                }
            }
        }
        None
    }

    fn has_estop(events: &[ActionEvent]) -> bool {
        events.iter().any(|e| matches!(e, ActionEvent::EStop))
    }

    fn cycle_value(events: &[ActionEvent]) -> Option<String> {
        events.iter().find_map(|e| match e {
            ActionEvent::CycleOutput { value, .. } => Some(value.clone()),
            _ => None,
        })
    }

    fn fresh_mapper() -> InputMapper {
        let mut m = InputMapper::new();
        m.profiles = vec![crate::bindings::presets::create_default_profile()];
        m.active_profile_id = "default".to_string();
        // Clear change-detection caches so each test starts deterministic.
        m.last_analog_values.clear();
        m.last_send_times.clear();
        m.last_button_states.clear();
        m
    }

    fn input_left_stick(x: f32, y: f32) -> InputState {
        let mut gp = GamepadState { connected: true, ..Default::default() };
        gp.left_stick.x = x;
        gp.left_stick.y = y;
        InputState {
            gamepad: gp,
            gyro: GyroState::default(),
            left_touchpad: TouchpadState::default(),
            right_touchpad: TouchpadState::default(),
        }
    }

    fn cmd_value(cmd: &MappedCommand) -> f64 {
        match cmd {
            MappedCommand::Topic { value, .. } | MappedCommand::WsInput { value, .. } => {
                value.as_f64().unwrap_or(f64::NAN)
            }
        }
    }

    // ── behavior (the "don't break anything" net) ───────────────────

    #[test]
    fn deflected_stick_emits_commands() {
        let mut m = fresh_mapper();
        let events = m.process(&input_left_stick(0.0, 0.9));
        let cmds = events.iter().filter(|e| matches!(e, ActionEvent::Command(_))).count();
        assert!(cmds > 0, "deflected stick must emit Command(s); got {:?}", events);
    }

    #[test]
    fn deflection_values_finite_and_nonzero() {
        let mut m = fresh_mapper();
        let events = m.process(&input_left_stick(0.0, 0.9));
        let mut saw_nonzero = false;
        for e in &events {
            if let ActionEvent::Command(cmd) = e {
                let v = cmd_value(cmd);
                assert!(v.is_finite(), "command value must be finite");
                if v.abs() > 1e-6 {
                    saw_nonzero = true;
                }
            }
        }
        assert!(saw_nonzero, "strong deflection should produce a non-zero command");
    }

    #[test]
    fn process_is_deterministic() {
        // Two independent mappers, same input → identical event stream.
        // This is the core invariant the profile-access refactor must
        // preserve (it changes HOW the active profile is read, not the math).
        let mut a = fresh_mapper();
        let mut b = fresh_mapper();
        let inp = input_left_stick(0.3, 0.7);
        let ea = a.process(&inp);
        let eb = b.process(&inp);
        assert_eq!(ea.len(), eb.len(), "event counts must match");
        assert_eq!(
            serde_json::to_string(&ea).unwrap(),
            serde_json::to_string(&eb).unwrap(),
            "event streams must be byte-identical",
        );
    }

    #[test]
    fn deadstick_after_deflection_emits_zero() {
        let mut m = fresh_mapper();
        let _ = m.process(&input_left_stick(0.0, 0.9)); // deflect
        let stop = m.process(&input_left_stick(0.0, 0.0)); // release
        let mut saw_zero = false;
        for e in &stop {
            if let ActionEvent::Command(cmd) = e {
                if cmd_value(cmd).abs() <= 1e-6 {
                    saw_zero = true;
                }
            }
        }
        assert!(saw_zero, "release must emit a zero stop command; got {:?}", stop);
    }

    // ── emission cadence (2026-07 latency audit lock-down) ──────────────

    #[test]
    fn held_deflection_reemits_every_tick() {
        // The value_active branch makes a held stick emit on EVERY
        // process() tick (~250 Hz at the 4 ms input loop); the client's
        // per-target throttle (THROTTLE_MS) caps the wire rate. The two
        // are load-bearing partners: this steady re-emit is what plugs
        // the throttle's trailing-edge drop for non-zero values. If this
        // test fails because held values stopped re-emitting, deadstick
        // recovery for mid-range setpoints rests solely on the 500 ms
        // heartbeat — revisit the throttle before shipping that.
        // Compare non-zero emissions only: the very first process() also
        // emits a one-time zero baseline for every idle binding
        // (heartbeat_due is true when a key has never sent), which then
        // goes quiet.
        fn nonzero_cmds(events: &[ActionEvent]) -> usize {
            events.iter()
                .filter(|e| match e {
                    ActionEvent::Command(cmd) => cmd_value(cmd).abs() > 0.001,
                    _ => false,
                })
                .count()
        }
        let mut m = fresh_mapper();
        let inp = input_left_stick(0.0, 0.9);
        let first = nonzero_cmds(&m.process(&inp));
        let second = nonzero_cmds(&m.process(&inp));
        assert!(first > 0, "deflection must emit");
        assert_eq!(first, second, "held deflection must re-emit each tick");
    }

    #[test]
    fn idle_zero_is_quiet_within_heartbeat_window() {
        // A resting stick must NOT stream zeros between heartbeats —
        // that's the no-signal-overkill half of the contract.
        let mut m = fresh_mapper();
        let _ = m.process(&input_left_stick(0.0, 0.9));
        let _ = m.process(&input_left_stick(0.0, 0.0)); // release → stop sent
        let idle = m.process(&input_left_stick(0.0, 0.0));
        let cmds = idle.iter()
            .filter(|e| matches!(e, ActionEvent::Command(_))).count();
        assert_eq!(cmds, 0, "resting stick must be quiet inside the heartbeat window");
    }

    #[test]
    fn heartbeat_reasserts_idle_value_after_interval() {
        // A dropped stop packet must be re-covered by the heartbeat:
        // backdate the send stamps past HEARTBEAT_MS and the idle zero
        // must be re-emitted.
        let mut m = fresh_mapper();
        let _ = m.process(&input_left_stick(0.0, 0.9));
        let _ = m.process(&input_left_stick(0.0, 0.0));
        let quiet = m.process(&input_left_stick(0.0, 0.0));
        assert_eq!(
            quiet.iter().filter(|e| matches!(e, ActionEvent::Command(_))).count(),
            0,
        );
        let past = Instant::now() - std::time::Duration::from_millis(HEARTBEAT_MS + 50);
        for t in m.last_send_times.values_mut() {
            *t = past;
        }
        let hb = m.process(&input_left_stick(0.0, 0.0));
        assert!(
            hb.iter().filter(|e| matches!(e, ActionEvent::Command(_))).count() > 0,
            "heartbeat must re-assert the idle value after HEARTBEAT_MS",
        );
    }

    #[test]
    fn no_profile_emits_nothing() {
        let mut m = fresh_mapper();
        m.profiles.clear();
        m.active_profile_id = "nope".to_string();
        assert!(m.process(&input_left_stick(0.0, 0.9)).is_empty());
    }

    // ── differential drive (tank mixing) ────────────────────────────

    fn diff_drive_profile() -> BindingProfile {
        analog_profile(AnalogBinding {
            input: AnalogInput::LeftStickY,
            action: AnalogAction::DifferentialDrive {
                topic: "/tracks".into(),
                left_channel: "left".into(),
                right_channel: "right".into(),
                throttle_transform: tf0(),
                turn_transform: tf0(),
            },
            enabled: true,
        })
    }

    #[test]
    fn diff_drive_mixes_throttle_and_turn() {
        // throttle (y) = 0.5, turn (x) = 0.5 → left = 1.0, right = 0.0.
        let mut m = mapper_with(diff_drive_profile());
        let ev = m.process(&input_left_stick(0.5, 0.5));
        approx(topic_cmd(&ev, "left").unwrap() as f32, 1.0);
        approx(topic_cmd(&ev, "right").unwrap() as f32, 0.0);
    }

    #[test]
    fn diff_drive_pure_throttle_drives_both_equally() {
        // throttle 0.8, no turn → both tracks 0.8.
        let mut m = mapper_with(diff_drive_profile());
        let ev = m.process(&input_left_stick(0.0, 0.8));
        approx(topic_cmd(&ev, "left").unwrap() as f32, 0.8);
        approx(topic_cmd(&ev, "right").unwrap() as f32, 0.8);
    }

    #[test]
    fn diff_drive_normalizes_when_sum_exceeds_one() {
        // throttle 1.0 + turn 1.0 → left 2.0, right 0.0; proportional
        // normalize divides by max (2.0) → left 1.0, right 0.0. Without
        // this the left track would saturate while right does nothing,
        // pulling the robot off the commanded arc.
        let mut m = mapper_with(diff_drive_profile());
        let ev = m.process(&input_left_stick(1.0, 1.0));
        approx(topic_cmd(&ev, "left").unwrap() as f32, 1.0);
        approx(topic_cmd(&ev, "right").unwrap() as f32, 0.0);
    }

    // ── modifiers (precision / speed boost) ──────────────────────────

    #[test]
    fn precision_modifier_scales_down() {
        let mut m = fresh_mapper();
        m.modifier_values.insert("precision".into(), 1.0); // full trigger
        approx(m.apply_modifiers(1.0), 0.3); // 1 - 1*(1-0.3) = 0.3
        m.modifier_values.insert("precision".into(), 0.5);
        approx(m.apply_modifiers(1.0), 0.65); // 1 - 0.5*0.7
    }

    #[test]
    fn speed_boost_modifier_scales_up_and_clamps() {
        let mut m = fresh_mapper();
        m.modifier_values.insert("speed_boost".into(), 1.0); // full trigger
        approx(m.apply_modifiers(0.5), 0.75); // 0.5 * 1.5
        approx(m.apply_modifiers(1.0), 1.0); // 1.5 → clamp 1.0
    }

    #[test]
    fn modifiers_compose_then_clamp() {
        let mut m = fresh_mapper();
        m.modifier_values.insert("precision".into(), 1.0);   // ×0.3
        m.modifier_values.insert("speed_boost".into(), 1.0); // ×1.5
        approx(m.apply_modifiers(1.0), 0.45); // 1 * 0.3 * 1.5
    }

    #[test]
    fn no_modifiers_is_identity() {
        let m = fresh_mapper();
        approx(m.apply_modifiers(0.7), 0.7);
        approx(m.apply_modifiers(-0.7), -0.7);
    }

    // ── digital actions ──────────────────────────────────────────────

    #[test]
    fn estop_button_emits_estop() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::Select,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::EStop,
            enabled: true,
        }));
        let ev = m.process(&input_buttons(&[("Select", true)]));
        assert!(has_estop(&ev), "Select press must emit EStop; got {ev:?}");
    }

    #[test]
    fn press_triggers_on_rising_edge_only() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::EStop,
            enabled: true,
        }));
        // Rising edge fires once.
        assert!(has_estop(&m.process(&input_buttons(&[("A", true)]))));
        // Held (still pressed, no new edge) does not re-fire.
        assert!(!has_estop(&m.process(&input_buttons(&[("A", true)]))));
        // Release does not fire a Press binding.
        assert!(!has_estop(&m.process(&input_buttons(&[("A", false)]))));
    }

    #[test]
    fn release_trigger_fires_on_falling_edge() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Release,
            action: DigitalAction::EStop,
            enabled: true,
        }));
        assert!(!has_estop(&m.process(&input_buttons(&[("A", true)])))); // press: no
        assert!(has_estop(&m.process(&input_buttons(&[("A", false)])))); // release: yes
    }

    #[test]
    fn hold_doubletap_longpress_are_not_yet_implemented() {
        // Lock the current TODO behaviour: these triggers never fire.
        // When implemented, this test breaks and prompts an update —
        // better than silently shipping a no-op binding.
        for trig in [ButtonTrigger::Hold, ButtonTrigger::DoubleTap, ButtonTrigger::LongPress] {
            let mut m = mapper_with(digital_profile(DigitalBinding {
                input: DigitalInput::A,
                trigger: trig,
                action: DigitalAction::EStop,
                enabled: true,
            }));
            assert!(!has_estop(&m.process(&input_buttons(&[("A", true)]))));
            assert!(!has_estop(&m.process(&input_buttons(&[("A", true)]))));
        }
    }

    #[test]
    fn disabled_binding_does_nothing() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::Select,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::EStop,
            enabled: false,
        }));
        assert!(!has_estop(&m.process(&input_buttons(&[("Select", true)]))));
    }

    #[test]
    fn toggle_output_flips_each_press() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::ToggleOutput { target_id: "motor".into() },
            enabled: true,
        }));
        m.process(&input_buttons(&[("A", true)]));   // press → true
        assert_eq!(m.toggle_states.get("motor"), Some(&true));
        m.process(&input_buttons(&[("A", false)]));  // release (no edge)
        m.process(&input_buttons(&[("A", true)]));   // press → false
        assert_eq!(m.toggle_states.get("motor"), Some(&false));
    }

    #[test]
    fn cycle_output_advances_and_wraps() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::A,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::CycleOutput {
                target_id: "mode".into(),
                values: vec!["a".into(), "b".into(), "c".into()],
            },
            enabled: true,
        }));
        let press = |m: &mut InputMapper| {
            let e = m.process(&input_buttons(&[("A", true)]));
            m.process(&input_buttons(&[("A", false)]));
            cycle_value(&e)
        };
        assert_eq!(press(&mut m).as_deref(), Some("b"));
        assert_eq!(press(&mut m).as_deref(), Some("c"));
        assert_eq!(press(&mut m).as_deref(), Some("a")); // wrap
    }

    #[test]
    fn show_panel_toggles_open_then_closed() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::Y,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::ShowPanel { panel_id: "poses".into() },
            enabled: true,
        }));
        let open = m.process(&input_buttons(&[("Y", true)]));
        assert!(open.iter().any(|e| matches!(e, ActionEvent::ShowPanel { panel_id } if panel_id == "poses")));
        assert_eq!(m.panel_state.active_panel_id.as_deref(), Some("poses"));

        m.process(&input_buttons(&[("Y", false)])); // release
        let close = m.process(&input_buttons(&[("Y", true)])); // same button again
        assert!(close.iter().any(|e| matches!(e, ActionEvent::HidePanel)));
        assert_eq!(m.panel_state.active_panel_id, None);
    }

    #[test]
    fn digital_direct_control_sends_fixed_value() {
        let mut m = mapper_with(digital_profile(DigitalBinding {
            input: DigitalInput::B,
            trigger: ButtonTrigger::Press,
            action: DigitalAction::DirectControl {
                target: ControlTarget::Topic {
                    topic: "/saint/horn".into(),
                    channel: "on".into(),
                    name: None,
                },
                value: 1.0,
            },
            enabled: true,
        }));
        let ev = m.process(&input_buttons(&[("B", true)]));
        approx(topic_cmd(&ev, "on").unwrap() as f32, 1.0);
    }

    // ── target routing ───────────────────────────────────────────────

    #[test]
    fn direct_control_routes_to_ws_input_target() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::RightStickX,
            action: AnalogAction::DirectControl {
                target: ControlTarget::WsInput {
                    sheet_id: "sheetA".into(),
                    input_id: "in1".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));
        let ev = m.process(&input_right_stick(0.8, 0.0));
        let routed = ev.iter().find_map(|e| match e {
            ActionEvent::Command(MappedCommand::WsInput { sheet_id, input_id, value }) =>
                Some((sheet_id.clone(), input_id.clone(), value.as_f64().unwrap_or(f64::NAN))),
            _ => None,
        });
        let (sheet, input, value) = routed.expect("expected a WsInput command");
        assert_eq!(sheet, "sheetA");
        assert_eq!(input, "in1");
        approx(value as f32, 0.8);
    }

    #[test]
    fn gyro_direct_control_preserves_degrees_per_second() {
        let mut m = mapper_with(analog_profile(AnalogBinding {
            input: AnalogInput::GyroPitch,
            action: AnalogAction::DirectControl {
                target: ControlTarget::WsInput {
                    sheet_id: "csharp_receiver".into(),
                    input_id: "GyroPitch".into(),
                    name: None,
                },
                transform: tf0(),
            },
            enabled: true,
        }));

        let ev = m.process(&input_gyro(537.25, -125.0, 88.0));
        let routed = ev.iter().find_map(|e| match e {
            ActionEvent::Command(MappedCommand::WsInput { input_id, value, .. })
                if input_id == "GyroPitch" => value.as_f64(),
            _ => None,
        });

        approx(routed.expect("expected GyroPitch command") as f32, 537.25);
    }

    // ── panel grid navigation ────────────────────────────────────────

    fn panel_profile(presets: usize, columns: u32, items_per_page: u32) -> BindingProfile {
        let mut p = BindingProfile::new("test", "Test");
        let presets = (0..presets)
            .map(|i| Preset {
                id: format!("p{i}"),
                name: format!("P{i}"),
                icon: None,
                color: None,
                preset_type: PresetType::Sound,
                data: PresetData::Sound(SoundPresetData {
                    sound_id: "s".into(),
                    volume: 1.0,
                    priority: 1,
                }),
            })
            .collect();
        p.preset_panels = vec![PresetPanel {
            id: "grid".into(),
            name: "Grid".into(),
            icon: "i".into(),
            color: "#fff".into(),
            presets,
            layout: PanelLayout::Grid,
            columns,
            items_per_page,
            source: None,
        }];
        p
    }

    #[test]
    fn navigate_grid_moves_within_bounds() {
        // 6 items, 4 columns, single page.
        let profile = panel_profile(6, 4, 8);
        let mut m = mapper_with(profile.clone());
        m.panel_state.active_panel_id = Some("grid".into());

        m.navigate_panel(&profile, &NavigateDirection::Right);
        assert_eq!(m.panel_state.selected_index, 1);

        m.panel_state.selected_index = 0;
        m.navigate_panel(&profile, &NavigateDirection::Down); // +columns
        assert_eq!(m.panel_state.selected_index, 4);

        m.navigate_panel(&profile, &NavigateDirection::Up); // back to row 0
        assert_eq!(m.panel_state.selected_index, 0);
    }

    #[test]
    fn navigate_grid_clamps_at_edges() {
        let profile = panel_profile(6, 4, 8);
        let mut m = mapper_with(profile.clone());
        m.panel_state.active_panel_id = Some("grid".into());

        // Up from row 0 is a no-op.
        m.navigate_panel(&profile, &NavigateDirection::Up);
        assert_eq!(m.panel_state.selected_index, 0);
        // Left from index 0 is a no-op.
        m.navigate_panel(&profile, &NavigateDirection::Left);
        assert_eq!(m.panel_state.selected_index, 0);
        // Right past the last item (index 5) is a no-op.
        m.panel_state.selected_index = 5;
        m.navigate_panel(&profile, &NavigateDirection::Right);
        assert_eq!(m.panel_state.selected_index, 5);
        // Down would land on index 9 (>= 6) → no-op.
        m.panel_state.selected_index = 5;
        m.navigate_panel(&profile, &NavigateDirection::Down);
        assert_eq!(m.panel_state.selected_index, 5);
    }

    #[test]
    fn navigate_grid_pages() {
        // 10 items, 4 columns, 8 per page → 2 pages.
        let profile = panel_profile(10, 4, 8);
        let mut m = mapper_with(profile.clone());
        m.panel_state.active_panel_id = Some("grid".into());

        m.navigate_panel(&profile, &NavigateDirection::NextPage);
        assert_eq!(m.panel_state.current_page, 1);
        assert_eq!(m.panel_state.selected_index, 8); // first item of page 2

        m.navigate_panel(&profile, &NavigateDirection::NextPage); // already last page
        assert_eq!(m.panel_state.current_page, 1);

        m.navigate_panel(&profile, &NavigateDirection::PrevPage);
        assert_eq!(m.panel_state.current_page, 0);
        assert_eq!(m.panel_state.selected_index, 0);
    }

    // ── benchmarks (#[ignore]; run with --ignored --nocapture) ───────

    #[test]
    #[ignore = "benchmark — run explicitly with --ignored --nocapture"]
    fn bench_process_per_frame() {
        let mut m = fresh_mapper();
        let inp = input_left_stick(0.4, 0.7); // actively deflected → emits every frame
        let n: u32 = 2_000_000;
        for _ in 0..10_000 {
            let _ = m.process(&inp);
        }
        let mut sink = 0usize;
        let t0 = Instant::now();
        for _ in 0..n {
            sink += m.process(&inp).len();
        }
        let el = t0.elapsed();
        println!(
            "\n[bench] InputMapper::process() per frame: {:.1} ns/call  ({:.0} calls/s, n={}, sink={})",
            el.as_nanos() as f64 / n as f64,
            n as f64 / el.as_secs_f64(),
            n,
            sink,
        );
    }
}
